---
- name: Clone eclipse.jdt.ls
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/dev/eclipse/eclipse.jdt.ls
- name: Build eclipse.jdt.ls
  command: ./mvnw clean install -DskipTests
  args:
    chdir: ~/dev/eclipse/eclipse.jdt.ls

- name: Clone java-debug
  git:
    repo: https://github.com/microsoft/java-debug
    dest: ~/dev/microsoft/java-debug
- name: Build java-debug
  command: ./mvnw clean install
  args:
    chdir: ~/dev/microsoft/java-debug

- name: Clone vscode-java-test
  git:
    repo: https://github.com/microsoft/vscode-java-test
    dest: ~/dev/microsoft/vscode-java-test
    force: true  # npm commands below modify the package.json

- name: Build vscode-java-test
  command: "{{ item }}"
  args:
    chdir: ~/dev/microsoft/vscode-java-test
  loop:
    - npm install
    - npm run build-plugin

- name: Create apps folder
  file:
    path: ~/apps/
    state: directory
    mode: 0700
- name: Create async-profiler folder
  file:
    path: ~/apps/async-profiler/
    state: directory
    mode: 0700
- name: Fetch sjk.jar
  get_url:
    url: https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.gridkit.jvmtool&a=sjk&v=LATEST
    dest: ~/apps/sjk.jar
- name: Get and unpack async-profiler
  unarchive:
    src: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.7/async-profiler-1.7-linux-x64.tar.gz
    dest: ~/apps/async-profiler/
    remote_src: true
    creates: ~/apps/async-profiler/profiler.sh
- name: Create jmc folder
  file:
    path: ~/apps/jmc/
    state: directory
    mode: 0700
- name: Get and unpack jmc
  unarchive:
    src: https://download.java.net/java/GA/jmc7/14/jmc-7_linux-x64_bin.tar.gz
    dest: ~/apps/jmc/
    remote_src: true
    creates: ~/apps/jmc/bin/jmc
    extra_opts:
      - --strip-components=1
- name: Create symlink for jmc
  file:
    src: ~/apps/jmc/bin/jmc
    dest: ~/bin/jmc
    state: link
